C      DUMMY INCLUDE FILE FOR GENERAL FILE VER-1.1
C
C  THIS FILE IS TO SURPRESS ERROR CODE OF LEVEL 0 ( NO REFERENCE OF
C INITIALIZED VARIABLES ) WITH THE INCLUDE FILE FOR THE GENERAL FILE
C VER-1.1.
C
      FLMODE(1) = FLMODE(1)
      HEADER(1) = HEADER(1)
      FMTAS     = FMTAS
      FMTAN     = FMTAN
      FMTAM     = FMTAM
      FMTI      = FMTI
      FMTF      = FMTF
C
C      END OF DUMMY INCLUDE FILE FOR GENERAL FILE VER-1.1
